### ISSUE TITLE
Datachecking functionality  

### ISSUE THREAD

**Issue by ghost** [jarathomas/InterVA5-R-Replicate#3]
Each of the verbal autopsy algorithms approaches data checking slightly differently. For example, this InterVA5 algorithm splits out the datachecking into a separate script (see below), whereas InterVA4 keeps everything in one function. It seems to us that the datachecking steps can be distilled to a core set of checks that likely will always need to be performed no matter which algorithm is being used; perhaps some of these core checks apply to every version of the input data and other checks are specific to a certain version.

Instead of having each algorithmic package do its own set of data checks, steps that likely contain unintentional differences across the packages, we recommend creating a standalone “datachecking package” that can be called as a dependency to each algorithmic implementation.  Having all of these checks in a single place would enable easy updates for all packages, standardize the consistency checks across packages, and make the user experience more seamless. Maintaining multiple code bases with substantial common code increases the time required to maintain the code in addition to increasing the likelihood that changes or bugfixes are not consistently applied.

https://github.com/verbal-autopsy-software/InterVA5/blob/d4f1779dad5c47ac39c8b7b914450d3b49e366e2/InterVA5_1.0/R/InterVA5.R#L269

**Comment by richardli** [comment]
thanks, this is something CrossVA is going to be able to take care of.
